const movies = [
    {
        country: 'Rusian',
        director: 'Titov A.V.',
        duration: '1ч 25мин',
        year: '2014',
        description: 'Очаровательные вампиры-соседи становятся героями фильма. Безумно смешная мокьюментари-комедия Тайки Вайтити',
        image: 'https://mauiislandfilms.files.wordpress.com/2014/06/what_we_do_in_the_shadows_ver2_xlg.jpg',
        trailerLink: 'https://yandex.ru/video/preview/2710294664333615035',
        thumbnail: 'https://pic.uma.media/pic/cardimage/cf/6c/cf6c01c7fd4d0cc9ab3759e329e0264d.jpg',
        movieId: '1',
        nameRU: 'Реальные упыри',
        nameEN: 'What We Do in the Shadows'  
    },
    {
        country: 'Rusian',
        director: 'Titov A.V.',
        duration: '1ч 25мин',
        year: '2014',
        description: 'Очаровательные вампиры-соседи становятся героями фильма. Безумно смешная мокьюментари-комедия Тайки Вайтити',
        image: 'https://mauiislandfilms.files.wordpress.com/2014/06/what_we_do_in_the_shadows_ver2_xlg.jpg',
        trailerLink: 'https://yandex.ru/video/preview/2710294664333615035',
        thumbnail: 'https://pic.uma.media/pic/cardimage/cf/6c/cf6c01c7fd4d0cc9ab3759e329e0264d.jpg',
        movieId: '2',
        nameRU: 'Реальные упыри',
        nameEN: 'What We Do in the Shadows'  
    },
    {
        country: 'Rusian',
        director: 'Titov A.V.',
        duration: '1ч 25мин',
        year: '2014',
        description: 'Очаровательные вампиры-соседи становятся героями фильма. Безумно смешная мокьюментари-комедия Тайки Вайтити',
        image: 'https://mauiislandfilms.files.wordpress.com/2014/06/what_we_do_in_the_shadows_ver2_xlg.jpg',
        trailerLink: 'https://yandex.ru/video/preview/2710294664333615035',
        thumbnail: 'https://pic.uma.media/pic/cardimage/cf/6c/cf6c01c7fd4d0cc9ab3759e329e0264d.jpg',
        movieId: '3',
        nameRU: 'Реальные упыри',
        nameEN: 'What We Do in the Shadows'  
    },
    {
        country: 'Rusian',
        director: 'Titov A.V.',
        duration: '1ч 25мин',
        year: '2014',
        description: 'Очаровательные вампиры-соседи становятся героями фильма. Безумно смешная мокьюментари-комедия Тайки Вайтити',
        image: 'https://mauiislandfilms.files.wordpress.com/2014/06/what_we_do_in_the_shadows_ver2_xlg.jpg',
        trailerLink: 'https://yandex.ru/video/preview/2710294664333615035',
        thumbnail: 'https://pic.uma.media/pic/cardimage/cf/6c/cf6c01c7fd4d0cc9ab3759e329e0264d.jpg',
        movieId: '4',
        nameRU: 'Реальные упыри',
        nameEN: 'What We Do in the Shadows'  
    },
    {
        country: 'Rusian',
        director: 'Titov A.V.',
        duration: '1ч 25мин',
        year: '2014',
        description: 'Очаровательные вампиры-соседи становятся героями фильма. Безумно смешная мокьюментари-комедия Тайки Вайтити',
        image: 'https://mauiislandfilms.files.wordpress.com/2014/06/what_we_do_in_the_shadows_ver2_xlg.jpg',
        trailerLink: 'https://yandex.ru/video/preview/2710294664333615035',
        thumbnail: 'https://pic.uma.media/pic/cardimage/cf/6c/cf6c01c7fd4d0cc9ab3759e329e0264d.jpg',
        movieId: '5',
        nameRU: 'Реальные упыри',
        nameEN: 'What We Do in the Shadows'  
    },
    {
        country: 'Rusian',
        director: 'Titov A.V.',
        duration: '1ч 25мин',
        year: '2014',
        description: 'Очаровательные вампиры-соседи становятся героями фильма. Безумно смешная мокьюментари-комедия Тайки Вайтити',
        image: 'https://mauiislandfilms.files.wordpress.com/2014/06/what_we_do_in_the_shadows_ver2_xlg.jpg',
        trailerLink: 'https://yandex.ru/video/preview/2710294664333615035',
        thumbnail: 'https://pic.uma.media/pic/cardimage/cf/6c/cf6c01c7fd4d0cc9ab3759e329e0264d.jpg',
        movieId: '6',
        nameRU: 'Реальные упыри',
        nameEN: 'What We Do in the Shadows'  
    },
    {
        country: 'Rusian',
        director: 'Titov A.V.',
        duration: '1ч 25мин',
        year: '2014',
        description: 'Очаровательные вампиры-соседи становятся героями фильма. Безумно смешная мокьюментари-комедия Тайки Вайтити',
        image: 'https://mauiislandfilms.files.wordpress.com/2014/06/what_we_do_in_the_shadows_ver2_xlg.jpg',
        trailerLink: 'https://yandex.ru/video/preview/2710294664333615035',
        thumbnail: 'https://pic.uma.media/pic/cardimage/cf/6c/cf6c01c7fd4d0cc9ab3759e329e0264d.jpg',
        movieId: '7',
        nameRU: 'Реальные упыри',
        nameEN: 'What We Do in the Shadows'  
    },
    {
        country: 'Rusian',
        director: 'Titov A.V.',
        duration: '1ч 25мин',
        year: '2014',
        description: 'Очаровательные вампиры-соседи становятся героями фильма. Безумно смешная мокьюментари-комедия Тайки Вайтити',
        image: 'https://mauiislandfilms.files.wordpress.com/2014/06/what_we_do_in_the_shadows_ver2_xlg.jpg',
        trailerLink: 'https://yandex.ru/video/preview/2710294664333615035',
        thumbnail: 'https://pic.uma.media/pic/cardimage/cf/6c/cf6c01c7fd4d0cc9ab3759e329e0264d.jpg',
        movieId: '8',
        nameRU: 'Реальные упыри',
        nameEN: 'What We Do in the Shadows'  
    },
    {
        country: 'Rusian',
        director: 'Titov A.V.',
        duration: '1ч 25мин',
        year: '2014',
        description: 'Очаровательные вампиры-соседи становятся героями фильма. Безумно смешная мокьюментари-комедия Тайки Вайтити',
        image: 'https://mauiislandfilms.files.wordpress.com/2014/06/what_we_do_in_the_shadows_ver2_xlg.jpg',
        trailerLink: 'https://yandex.ru/video/preview/2710294664333615035',
        thumbnail: 'https://pic.uma.media/pic/cardimage/cf/6c/cf6c01c7fd4d0cc9ab3759e329e0264d.jpg',
        movieId: '9',
        nameRU: 'Реальные упыри',
        nameEN: 'What We Do in the Shadows'  
    },
    {
        country: 'Rusian',
        director: 'Titov A.V.',
        duration: '1ч 25мин',
        year: '2014',
        description: 'Очаровательные вампиры-соседи становятся героями фильма. Безумно смешная мокьюментари-комедия Тайки Вайтити',
        image: 'https://mauiislandfilms.files.wordpress.com/2014/06/what_we_do_in_the_shadows_ver2_xlg.jpg',
        trailerLink: 'https://yandex.ru/video/preview/2710294664333615035',
        thumbnail: 'https://pic.uma.media/pic/cardimage/cf/6c/cf6c01c7fd4d0cc9ab3759e329e0264d.jpg',
        movieId: '10',
        nameRU: 'Реальные упыри',
        nameEN: 'What We Do in the Shadows'  
    },
    {
        country: 'Rusian',
        director: 'Titov A.V.',
        duration: '1ч 25мин',
        year: '2014',
        description: 'Очаровательные вампиры-соседи становятся героями фильма. Безумно смешная мокьюментари-комедия Тайки Вайтити',
        image: 'https://mauiislandfilms.files.wordpress.com/2014/06/what_we_do_in_the_shadows_ver2_xlg.jpg',
        trailerLink: 'https://yandex.ru/video/preview/2710294664333615035',
        thumbnail: 'https://pic.uma.media/pic/cardimage/cf/6c/cf6c01c7fd4d0cc9ab3759e329e0264d.jpg',
        movieId: '11',
        nameRU: 'Реальные упыри',
        nameEN: 'What We Do in the Shadows'  
    },
    {
        country: 'Rusian',
        director: 'Titov A.V.',
        duration: '1ч 25мин',
        year: '2014',
        description: 'Очаровательные вампиры-соседи становятся героями фильма. Безумно смешная мокьюментари-комедия Тайки Вайтити',
        image: 'https://mauiislandfilms.files.wordpress.com/2014/06/what_we_do_in_the_shadows_ver2_xlg.jpg',
        trailerLink: 'https://yandex.ru/video/preview/2710294664333615035',
        thumbnail: 'https://pic.uma.media/pic/cardimage/cf/6c/cf6c01c7fd4d0cc9ab3759e329e0264d.jpg',
        movieId: '12',
        nameRU: 'Реальные упыри',
        nameEN: 'What We Do in the Shadows'  
    },
    {
        country: 'Rusian',
        director: 'Titov A.V.',
        duration: '1ч 25мин',
        year: '2014',
        description: 'Очаровательные вампиры-соседи становятся героями фильма. Безумно смешная мокьюментари-комедия Тайки Вайтити',
        image: 'https://mauiislandfilms.files.wordpress.com/2014/06/what_we_do_in_the_shadows_ver2_xlg.jpg',
        trailerLink: 'https://yandex.ru/video/preview/2710294664333615035',
        thumbnail: 'https://pic.uma.media/pic/cardimage/cf/6c/cf6c01c7fd4d0cc9ab3759e329e0264d.jpg',
        movieId: '10',
        nameRU: 'Реальные упыри',
        nameEN: 'What We Do in the Shadows'  
    },
    {
        country: 'Rusian',
        director: 'Titov A.V.',
        duration: '1ч 25мин',
        year: '2014',
        description: 'Очаровательные вампиры-соседи становятся героями фильма. Безумно смешная мокьюментари-комедия Тайки Вайтити',
        image: 'https://mauiislandfilms.files.wordpress.com/2014/06/what_we_do_in_the_shadows_ver2_xlg.jpg',
        trailerLink: 'https://yandex.ru/video/preview/2710294664333615035',
        thumbnail: 'https://pic.uma.media/pic/cardimage/cf/6c/cf6c01c7fd4d0cc9ab3759e329e0264d.jpg',
        movieId: '11',
        nameRU: 'Реальные упыри',
        nameEN: 'What We Do in the Shadows'  
    },
    {
        country: 'Rusian',
        director: 'Titov A.V.',
        duration: '1ч 25мин',
        year: '2014',
        description: 'Очаровательные вампиры-соседи становятся героями фильма. Безумно смешная мокьюментари-комедия Тайки Вайтити',
        image: 'https://mauiislandfilms.files.wordpress.com/2014/06/what_we_do_in_the_shadows_ver2_xlg.jpg',
        trailerLink: 'https://yandex.ru/video/preview/2710294664333615035',
        thumbnail: 'https://pic.uma.media/pic/cardimage/cf/6c/cf6c01c7fd4d0cc9ab3759e329e0264d.jpg',
        movieId: '12',
        nameRU: 'Реальные упыри',
        nameEN: 'What We Do in the Shadows'  
    }
  ];

  const savedMovies = [
    {
        country: 'Rusian',
        director: 'Titov A.V.',
        duration: '1ч 25мин',
        year: '2014',
        description: 'Очаровательные вампиры-соседи становятся героями фильма. Безумно смешная мокьюментари-комедия Тайки Вайтити',
        image: 'https://mauiislandfilms.files.wordpress.com/2014/06/what_we_do_in_the_shadows_ver2_xlg.jpg',
        trailerLink: 'https://yandex.ru/video/preview/2710294664333615035',
        thumbnail: 'https://pic.uma.media/pic/cardimage/cf/6c/cf6c01c7fd4d0cc9ab3759e329e0264d.jpg',
        movieId: '1',
        nameRU: 'Реальные упыри',
        nameEN: 'What We Do in the Shadows'  
    },
    {
        country: 'Rusian',
        director: 'Titov A.V.',
        duration: '1ч 25мин',
        year: '2014',
        description: 'Очаровательные вампиры-соседи становятся героями фильма. Безумно смешная мокьюментари-комедия Тайки Вайтити',
        image: 'https://mauiislandfilms.files.wordpress.com/2014/06/what_we_do_in_the_shadows_ver2_xlg.jpg',
        trailerLink: 'https://yandex.ru/video/preview/2710294664333615035',
        thumbnail: 'https://pic.uma.media/pic/cardimage/cf/6c/cf6c01c7fd4d0cc9ab3759e329e0264d.jpg',
        movieId: '2',
        nameRU: 'Реальные упыри',
        nameEN: 'What We Do in the Shadows'  
    },
    {
        country: 'Rusian',
        director: 'Titov A.V.',
        duration: '1ч 25мин',
        year: '2014',
        description: 'Очаровательные вампиры-соседи становятся героями фильма. Безумно смешная мокьюментари-комедия Тайки Вайтити',
        image: 'https://mauiislandfilms.files.wordpress.com/2014/06/what_we_do_in_the_shadows_ver2_xlg.jpg',
        trailerLink: 'https://yandex.ru/video/preview/2710294664333615035',
        thumbnail: 'https://pic.uma.media/pic/cardimage/cf/6c/cf6c01c7fd4d0cc9ab3759e329e0264d.jpg',
        movieId: '3',
        nameRU: 'Реальные упыри',
        nameEN: 'What We Do in the Shadows'  
    }
  ];


  export { movies, savedMovies } 